import { Scholarship, Task, DocumentItem, ActivityItem, ProfileData, GapYearData, StorySection } from '@/types';

// Helper to format dates relative to today
const getRelativeDate = (offsetDays: number): string => {
  const d = new Date();
  d.setDate(d.getDate() + offsetDays);
  return d.toISOString().split('T')[0];
};

export const INITIAL_SCHOLARSHIPS: Scholarship[] = [
  {
    id: 'sch-1',
    name: 'Turkiye Burslari Scholarships',
    university: 'Selected Turkish Universities (ODTU, Bogazici, ITU)',
    organization: 'YTB (Presidency for Turks Abroad and Related Communities)',
    country: 'Turkey',
    degreeLevel: 'Undergraduate',
    fieldOfStudy: 'Computer Science & Software Engineering',
    intake: 'Fall 2027',
    academicYear: '2027-2028',
    fundingType: 'Full Ride (Tuition + Living + Travel)',
    awardAmount: '100% Tuition + 3,500 TRY/mo stipend + Dormitory + Flights + Health Insurance',
    websiteUrl: 'https://www.turkiyeburslari.gov.tr',
    portalUrl: 'https://tbbs.turkiyeburslari.gov.tr',
    deadline: getRelativeDate(14), // 14 days from now
    earlyDeadline: getRelativeDate(7),
    notificationDate: getRelativeDate(120),
    status: 'Preparing',
    priority: 'High',
    notes: 'Requires 1-year Turkish language preparatory program. Very competitive for engineering applicants from Pakistan.',
    tags: ['Full Ride', 'Turkey', 'Engineering', 'Government'],
    requirements: [
      { id: 'req-1', name: 'Letter of Intent (Motivation Essay)', type: 'Essay', status: 'In Progress', dueDate: getRelativeDate(5), notes: 'Highlight gap-year initiatives and community robotics teaching' },
      { id: 'req-2', name: 'Intermediate / HSSC Marksheet & Certificate', type: 'Document', status: 'Ready', linkedDocId: 'doc-2' },
      { id: 'req-3', name: 'Academic Recommendation Letter 1', type: 'Recommendation', status: 'Ready', linkedDocId: 'doc-4' },
      { id: 'req-4', name: 'Academic Recommendation Letter 2', type: 'Recommendation', status: 'In Progress', dueDate: getRelativeDate(6), notes: 'Follow up with Physics lecturer' },
      { id: 'req-5', name: 'Valid Passport', type: 'Document', status: 'Ready', linkedDocId: 'doc-1' },
      { id: 'req-6', name: 'Extracurricular Achievement Certificates', type: 'Portfolio', status: 'Ready', linkedDocId: 'doc-6' },
      { id: 'req-7', name: 'Proposed Study Plan / Research Intent', type: 'Essay', status: 'Not Started', dueDate: getRelativeDate(10) },
    ],
    linkedActivityIds: ['act-1', 'act-2'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sch-2',
    name: 'MEXT Japanese Government Undergraduate Scholarship',
    university: 'National Universities of Japan (Tokyo Tech, Kyoto, Tohoku)',
    organization: 'Ministry of Education, Culture, Sports, Science and Technology (MEXT)',
    country: 'Japan',
    degreeLevel: 'Undergraduate',
    fieldOfStudy: 'Natural Sciences A (Information Engineering)',
    intake: 'Spring 2027',
    academicYear: '2027-2028',
    fundingType: 'Full Ride (Tuition + Living + Travel)',
    awardAmount: '100% Tuition + ¥120,000/mo + Roundtrip flights + 1-yr Japanese preparatory schooling',
    websiteUrl: 'https://www.pk.emb-japan.go.jp',
    portalUrl: 'https://www.studyinjapan.go.jp/en/',
    deadline: getRelativeDate(3), // Critical deadline in 3 days!
    status: 'Ready to Apply',
    priority: 'High',
    notes: 'Written exams in Islamabad: Mathematics B, Physics, Chemistry, English. Target high score in Math.',
    tags: ['Full Ride', 'Japan', 'Government', 'High Prestige'],
    requirements: [
      { id: 'm-req-1', name: 'MEXT Application Form 2027', type: 'Document', status: 'Ready' },
      { id: 'm-req-2', name: 'Official High School Transcripts (Attested)', type: 'Document', status: 'Ready', linkedDocId: 'doc-2' },
      { id: 'm-req-3', name: 'Certificate of Graduation / Expected Graduation', type: 'Document', status: 'Ready' },
      { id: 'm-req-4', name: 'Principal Recommendation Letter (Confidential Seal)', type: 'Recommendation', status: 'Ready', linkedDocId: 'doc-4' },
      { id: 'm-req-5', name: 'Medical Certificate (Form MEXT)', type: 'Document', status: 'Ready' },
      { id: 'm-req-6', name: 'Field of Study and Study Program Plan', type: 'Essay', status: 'Ready' },
    ],
    linkedActivityIds: ['act-2', 'act-3'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sch-3',
    name: 'Islamic Development Bank (IsDB) Undergraduate Scholarship',
    university: 'Top 50 Partner Universities in OIC & International Countries',
    organization: 'IsDB Islamic Development Bank',
    country: 'Saudi Arabia / International',
    degreeLevel: 'Undergraduate',
    fieldOfStudy: 'Computer Systems & AI for Development',
    intake: 'Fall 2027',
    academicYear: '2027-2028',
    fundingType: 'Full Ride (Tuition + Living + Travel)',
    awardAmount: 'Tuition fees + Monthly living allowance + Book allowance + Health insurance',
    websiteUrl: 'https://www.isdb.org/scholarships',
    deadline: getRelativeDate(45),
    status: 'Researching',
    priority: 'Medium',
    notes: 'Bonded scholarship: Requires graduates to serve their home country community for years equal to duration of study.',
    tags: ['Full Ride', 'OIC', 'Development Focus'],
    requirements: [
      { id: 'isdb-1', name: 'Secondary School Certificate / Equivalence', type: 'Document', status: 'Ready', linkedDocId: 'doc-2' },
      { id: 'isdb-2', name: 'Community Contribution & Impact Statement', type: 'Essay', status: 'Not Started', dueDate: getRelativeDate(20) },
      { id: 'isdb-3', name: 'Proof of English Proficiency (IELTS 7.5)', type: 'Test', status: 'Ready', linkedDocId: 'doc-5' },
    ],
    linkedActivityIds: ['act-1'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sch-4',
    name: 'KAIST Undergraduate International Scholarship',
    university: 'KAIST (Korea Advanced Institute of Science and Technology)',
    organization: 'KAIST Office of Admissions',
    country: 'South Korea',
    degreeLevel: 'Undergraduate',
    fieldOfStudy: 'School of Computing',
    intake: 'Spring 2027',
    academicYear: '2026-2027',
    fundingType: 'Full Tuition',
    awardAmount: '100% Tuition waiver for 8 semesters + 350,000 KRW/month living allowance',
    websiteUrl: 'https://admission.kaist.ac.kr/intl-undergraduate/',
    portalUrl: 'https://apply.kaist.ac.kr',
    deadline: getRelativeDate(28),
    status: 'Preparing',
    priority: 'High',
    notes: 'Online interview conducted via Zoom if shortlisted. 100% courses taught in English.',
    tags: ['South Korea', 'Top Tech', 'Tuition Waiver'],
    requirements: [
      { id: 'k-1', name: 'One Recommendation Letter via Online Portal', type: 'Recommendation', status: 'In Progress', notes: 'Waiting for teacher submission link' },
      { id: 'k-2', name: 'Standardized Test Score (SAT / High School Rank)', type: 'Test', status: 'Ready' },
      { id: 'k-3', name: 'Statement of Purpose (3 Prompts)', type: 'Essay', status: 'In Progress', dueDate: getRelativeDate(12) },
      { id: 'k-4', name: 'Financial Resource Statement', type: 'Financial', status: 'Ready', linkedDocId: 'doc-7' },
    ],
    linkedActivityIds: ['act-2', 'act-3'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sch-5',
    name: 'DAAD Helmut-Schmidt Scholarship Program',
    university: 'University of Passau & Willy Brandt School Erfurt',
    organization: 'German Academic Exchange Service (DAAD)',
    country: 'Germany',
    degreeLevel: "Master's",
    fieldOfStudy: 'Public Policy, Governance & Tech Policy',
    intake: 'Winter 2027',
    academicYear: '2027-2028',
    fundingType: 'Full Ride (Tuition + Living + Travel)',
    awardAmount: '€934/month + Travel allowance + Health insurance + 6-month intensive German course',
    websiteUrl: 'https://www2.daad.de',
    deadline: getRelativeDate(80),
    status: 'Researching',
    priority: 'Low',
    notes: 'For developing nations leaders and innovators. Need strong socio-political relevance.',
    tags: ['Germany', 'Europe', 'DAAD', 'Living Allowance'],
    requirements: [
      { id: 'daad-1', name: 'Europass CV format', type: 'Document', status: 'Not Started' },
      { id: 'daad-2', name: 'Letter of Motivation with Political/Development rationale', type: 'Essay', status: 'Not Started' },
    ],
    linkedActivityIds: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'tsk-1',
    title: 'Finalize Turkiye Burslari Letter of Intent (Gap Year highlights)',
    description: 'Refine section explaining why I took a gap year and how building robotics mentorship shaped my academic clarity.',
    dueDate: getRelativeDate(0), // Today!
    dueTime: '17:00',
    completed: false,
    priority: 'High',
    category: 'Essay',
    scholarshipId: 'sch-1',
    scholarshipName: 'Turkiye Burslari Scholarships',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tsk-2',
    title: 'Deliver physical envelope of MEXT application to Embassy courier',
    description: 'Ensure sealed recommendation letters and notarized matric/inter marksheets are enclosed.',
    dueDate: getRelativeDate(0), // Today!
    dueTime: '14:30',
    completed: false,
    priority: 'High',
    category: 'Scholarship',
    scholarshipId: 'sch-2',
    scholarshipName: 'MEXT Japanese Government',
    documentId: 'doc-4',
    documentName: 'Academic Recommendation Letter',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tsk-3',
    title: 'Verify Passport validity and schedule renewal appointment',
    description: 'Passport expires in less than 3 months. Embassies require minimum 6-12 months validity!',
    dueDate: getRelativeDate(0), // Today!
    completed: false,
    priority: 'High',
    category: 'Documents',
    documentId: 'doc-1',
    documentName: 'Valid Passport',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tsk-4',
    title: 'Download and review KAIST SOP Prompt 2 (Technical Challenges)',
    description: 'Draft 500 words addressing the robotics troubleshooting experience and self-taught programming.',
    dueDate: getRelativeDate(1), // Tomorrow
    completed: false,
    priority: 'Medium',
    category: 'Essay',
    scholarshipId: 'sch-4',
    scholarshipName: 'KAIST Undergraduate Scholarship',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tsk-5',
    title: 'Request second teacher recommendation from Sir Kamran (Physics)',
    description: 'Send updated CV and bullet points of lab projects completed during FSC.',
    dueDate: getRelativeDate(2),
    completed: false,
    priority: 'High',
    category: 'Recommendation',
    scholarshipId: 'sch-1',
    scholarshipName: 'Turkiye Burslari Scholarships',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tsk-6',
    title: 'Notarize bank financial declaration for KAIST sponsorship form',
    dueDate: getRelativeDate(4),
    completed: false,
    priority: 'Medium',
    category: 'Finance',
    documentId: 'doc-7',
    documentName: "Father's Income Certificate & Bank Statement",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tsk-7',
    title: 'Review MEXT past Mathematics B exam questions (Calculus & Vectors)',
    dueDate: getRelativeDate(5),
    completed: false,
    priority: 'Medium',
    category: 'Test',
    scholarshipId: 'sch-2',
    scholarshipName: 'MEXT Japanese Government',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tsk-8',
    title: 'Weekly Scholarship Pipeline Review & Calendar update',
    dueDate: getRelativeDate(6),
    completed: false,
    priority: 'Low',
    category: 'General',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tsk-9',
    title: 'Order certified English translation of Birth Certificate',
    dueDate: getRelativeDate(-2), // 2 days overdue!
    completed: false,
    priority: 'High',
    category: 'Documents',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tsk-10',
    title: 'Attest Intermediate Board result sheet at IBCC regional office',
    dueDate: getRelativeDate(-4),
    completed: true,
    completedAt: getRelativeDate(-3),
    priority: 'High',
    category: 'Documents',
    documentId: 'doc-2',
    documentName: 'HSSC Intermediate Marksheet',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
];

export const INITIAL_DOCUMENTS: DocumentItem[] = [
  {
    id: 'doc-1',
    name: 'Government Passport (Machine Readable)',
    category: 'Identity',
    status: 'Ready',
    description: '36-page national passport issued by DGI&P Pakistan.',
    fileName: 'Passport_Scan_Official.pdf',
    fileSize: 1450200,
    fileUrl: '',
    issueDate: '2021-12-10',
    expiryDate: getRelativeDate(55), // Expiring in 55 days! Triggers proactive Needs Attention alert
    notes: 'Urgent: Must apply for urgent 10-year renewal at Passport Office Lahore.',
    linkedScholarshipIds: ['sch-1', 'sch-2', 'sch-3', 'sch-4'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'doc-2',
    name: 'HSSC Pre-Engineering Certificate & Transcript (IBCC Attested)',
    category: 'Academic',
    status: 'Ready',
    description: 'Marks: 1042/1100 (94.7% Grade A-1). Attested by Board of Intermediate & Secondary Education and IBCC.',
    fileName: 'HSSC_Transcript_IBCC_Attested.pdf',
    fileSize: 2890100,
    fileUrl: '',
    issueDate: '2025-08-15',
    linkedScholarshipIds: ['sch-1', 'sch-2', 'sch-3', 'sch-4'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'doc-3',
    name: 'Secondary School Certificate (Matriculation Science)',
    category: 'Academic',
    status: 'Ready',
    description: 'Marks: 1058/1100 (96.2%). Verified copy with seal.',
    fileName: 'Matric_Certificate_Verified.pdf',
    fileSize: 1920000,
    fileUrl: '',
    issueDate: '2023-07-20',
    linkedScholarshipIds: ['sch-1', 'sch-2'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'doc-4',
    name: 'Academic Recommendation Letter - Prof. Tariq Rashid (Maths)',
    category: 'Recommendation',
    status: 'Ready',
    description: 'Detailed evaluation of analytical problem-solving and ranking 1st in collegiate math league.',
    fileName: 'Recommendation_Prof_Tariq_Rashid.pdf',
    fileSize: 840500,
    fileUrl: '',
    issueDate: '2026-08-01',
    linkedScholarshipIds: ['sch-1', 'sch-2'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'doc-5',
    name: 'IELTS Academic Test Report Form (Overall 7.5)',
    category: 'Test',
    status: 'Ready',
    description: 'Scores: Listening 8.5, Reading 8.0, Writing 7.0, Speaking 7.0. CEFR C1 level.',
    fileName: 'IELTS_TRF_Official_Report.pdf',
    fileSize: 1104000,
    fileUrl: '',
    issueDate: '2026-01-18',
    expiryDate: '2028-01-18',
    linkedScholarshipIds: ['sch-1', 'sch-3', 'sch-4'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'doc-6',
    name: 'Comprehensive Academic Curriculum Vitae (CV)',
    category: 'CV',
    status: 'In Progress',
    description: 'Two-page academic CV detailing gap-year research projects, olympiad rankings, and leadership.',
    fileName: 'CV_Academic_Updated_2026.pdf',
    fileSize: 520000,
    fileUrl: '',
    linkedScholarshipIds: ['sch-1', 'sch-2', 'sch-3', 'sch-4', 'sch-5'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'doc-7',
    name: "Father's Income Certificate & Bank Statement",
    category: 'Financial',
    status: 'Ready',
    description: 'Tax returns and 6-month bank maintenance certificate attested by Branch Manager.',
    fileName: 'Financial_Affidavit_Bank_Statement.pdf',
    fileSize: 3100000,
    fileUrl: '',
    issueDate: '2026-09-01',
    expiryDate: getRelativeDate(85),
    linkedScholarshipIds: ['sch-4'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
];

export const INITIAL_ACTIVITIES: ActivityItem[] = [
  {
    id: 'act-1',
    title: 'Founder & Volunteer Lead - Community Robotics Workshop',
    type: 'Leadership',
    organization: 'Youth STEM Initiative Punjab',
    role: 'Founder & Project Director',
    startDate: '2025-10-01',
    isCurrent: true,
    description: 'Designed free 8-week Arduino and C++ robotics curriculum for 60+ underprivileged students in government schools.',
    impact: 'Raised PKR 250,000 for kit sponsorships; 4 student teams qualified for regional science exhibition.',
    achievements: 'Featured in local education newspaper; partnered with 3 local public institutions.',
    hoursPerWeek: 12,
    location: 'Lahore, Pakistan',
    linkedScholarshipIds: ['sch-1', 'sch-3'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'act-2',
    title: 'National Science & Mathematics Olympiad Finalist',
    type: 'Competition',
    organization: 'Pakistan Science Foundation & NSTC',
    role: 'Individual Competitor',
    startDate: '2024-03-01',
    endDate: '2024-11-20',
    isCurrent: false,
    description: 'Rigorous national competition across advanced mathematics, algorithmic thinking, and problem solving.',
    impact: 'Ranked top 15 out of 8,500+ participants nationally.',
    achievements: 'Bronze Medalist and selected for National Science Talent Contest training camp.',
    hoursPerWeek: 10,
    location: 'Islamabad, Pakistan',
    linkedScholarshipIds: ['sch-1', 'sch-2', 'sch-4'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'act-3',
    title: 'Open Source Software Contributor & Web Lead',
    type: 'Project',
    organization: 'Urdu Language Tech Collective',
    role: 'Core Contributor',
    startDate: '2025-06-01',
    isCurrent: true,
    description: 'Building open-source educational flashcard and dictionary tools accessible in Urdu and regional languages.',
    impact: 'Repository starred by 400+ developers with 1,200 active monthly student users.',
    achievements: 'Presented lightening talk at local Tech Meetup Lahore.',
    hoursPerWeek: 8,
    location: 'Remote / Pakistan',
    url: 'https://github.com/scholarship-student/urdu-learn-tools',
    linkedScholarshipIds: ['sch-2', 'sch-4'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
];

export const INITIAL_PROFILE: ProfileData = {
  fullName: 'Muhammad Dawood Khan',
  email: 'dawood.scholarships@gmail.com',
  phone: '+92 300 1234567',
  country: 'Pakistan',
  city: 'Lahore',
  languages: ['Urdu (Native)', 'English (Fluent - C1 IELTS 7.5)', 'Punjabi (Conversational)', 'Turkish (Beginner A1)'],
  intendedDegree: "Bachelor of Science (Undergraduate)",
  intendedField: 'Computer Science, Artificial Intelligence & Software Engineering',
  careerGoals: 'To become a specialized research software engineer building scalable computational infrastructure, and later establish an applied AI research laboratory in Pakistan.',
  longTermVision: 'Democratize accessible educational and agricultural AI technologies across developing nations, bridging the digital equity gap.',
  whyStudyAbroad: 'To access cutting-edge research facilities, world-class professors, diverse global perspectives, and return with technological leadership to solve real-world problems.',
  whyThisField: 'Computer Science provides the highest leverage toolset to solve resource constraints in healthcare, education, and public systems in developing countries.',
  education: [
    {
      id: 'edu-1',
      institution: 'Punjab Group of Colleges, Lahore',
      program: 'Higher Secondary School Certificate (FSc Pre-Engineering)',
      grade: '1042 / 1100 (94.7% Grade A-1)',
      startYear: '2023',
      endYear: '2025',
      achievements: 'College Merit Scholarship holder, President of Mathematics & Computing Society.',
    },
    {
      id: 'edu-2',
      institution: 'Divisional Public School & College (DPS)',
      program: 'Secondary School Certificate (Matriculation Science)',
      grade: '1058 / 1100 (96.2% Distinction)',
      startYear: '2021',
      endYear: '2023',
      achievements: 'Gold Medal in School Annual Science Exhibition, 1st position in regional quiz bowl.',
    }
  ]
};

export const INITIAL_GAP_YEAR: GapYearData = {
  whyTookGapYear: 'Rather than rushing into a local program without international financial support, I intentionally stepped back to focus full-time on international scholarship applications, self-directed research, community teaching, and preparing for competitive exams like MEXT and SAT.',
  whatAmIDoing: 'Directing the Youth STEM Initiative teaching robotics to 60+ underprivileged students; completing MIT OpenCourseWare 6.0001 Computer Science; contributing to open-source Urdu technology; and preparing scholarship applications.',
  whatIHaveLearned: 'Independence, extreme time management, grant writing, cross-cultural communication, and the discipline of self-motivated research without institutional scaffolding.',
  skillsDeveloped: 'Python & C++ development, Embedded Systems (Arduino/ESP32), technical writing, IELTS preparation, pedagogical curriculum design, and organizational leadership.',
  projectsCompleted: 'Low-cost water quality monitor using ESP32; Community Robotics Curriculum; Urdu educational toolkit with 1,200+ monthly active learners.',
  goalsForYear: 'Secure a fully-funded international scholarship (MEXT, Turkiye Burslari, or KAIST), publish open-source STEM curriculum, and achieve fluency in basic host country language.'
};

export const INITIAL_STORY_SECTIONS: StorySection[] = [
  {
    id: 'story-1',
    title: 'Personal Background & Origins',
    content: 'Growing up in Lahore within a middle-class family where education was revered above all material wealth, I was taught by my parents that intellectual curiosity is the only currency that never depreciates. Watching my father manage household expenses with meticulous discipline inspired my drive to achieve merit-based educational independence.',
    promptNotes: 'Useful for: Background essays, Tell us about yourself, Family context, Financial hardship questions.',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'story-2',
    title: 'The Turning Point: Discovering Computer Science',
    content: 'When our school received three decommissioned desktop computers in 9th grade, I spent after-school hours understanding how a few lines of logic could animate an entire machine. With no home broadband initially, I downloaded programming documentation onto a USB stick at a cyber café and read text files late into the night.',
    promptNotes: 'Useful for: Why this field?, How did your interest begin?, Early academic exploration.',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'story-3',
    title: 'Overcoming Resource Constraints',
    content: 'Advanced robotics components were financially inaccessible in my neighborhood. Instead of resigning, my peers and I salvaged motors and sensors from discarded electronic toys and appliances. This taught me that real engineering is not defined by pristine lab budgets, but by resourceful ingenuity under severe constraints.',
    promptNotes: 'Useful for: Challenge overcome, Resilience, How you deal with failure or limitations.',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'story-4',
    title: 'Core Values & Community Contribution',
    content: 'Privilege carries an obligation to mentor. Establishing the Youth STEM Initiative in Lahore showed me that teaching is the ultimate test of understanding. Seeing a 13-year-old student from an underprivileged school successfully code their first autonomous obstacle-avoiding car reaffirmed my commitment to knowledge democratization.',
    promptNotes: 'Useful for: Leadership essays, Contribution to campus community, Diversity & service.',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'story-5',
    title: 'Long-term Vision & Contribution to Pakistan',
    content: 'My objective after completing international undergraduate studies in computing is to bridge global technological innovations with developing world infrastructure. I intend to lead research in high-efficiency AI systems adaptable to low-bandwidth environments, empowering smart municipal and agrarian solutions across South Asia.',
    promptNotes: 'Useful for: Post-graduation goals, How will this scholarship help your home country?, 5-10 year vision.',
    updatedAt: new Date().toISOString(),
  }
];
